### ISSUE TITLE
Runtime detected an invalid program.

### ISSUE THREAD

**Issue by haldiggs** [kingpin2k/HTMLBarsHelper#6]
odd. as long as I have optimizations off the .hbs gets injected and works. As soon as I turn them on I get an error.

An exception of type 'System.InvalidProgramException' occurred in Jurassic.dll but was not handled in user code

The error seems to be coming from the Jurassic.dll 

I'm at a loss right now.
in my index view this is the code I am using to flip the injection.

`@if (System.Web.Optimization.BundleTable.EnableOptimizations)
{
    @Scripts.Render(BundleConfig.HbsHomeTemplatesPath)
}
else
{
    @HTMLBarsHelper.RawTemplateInjector.InjectRawTemplates("~/Scripts/homeApp/templates", new[] { "*.hbs" })
}
`

**Comment by kingpin2k** [comment]
Hmmm, that's interesting, can you expound on your versions environment etc?

**Comment by haldiggs** [comment]
Will do when I get back in the office. Appreciate any help. Love the fact
that you created this product.

On Saturday, January 30, 2016, kingpin2k notifications@github.com wrote:

> Hmmm, that's interesting, can you expound on your versions environment etc?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kingpin2k/HTMLBarsHelper/issues/6#issuecomment-177320318
> .

## 

Hal D. Diggs
https://www.mcpvirtualbusinesscard.com/VBCServer/haldiggs/card - "Non
sibi sed patriae" (Not for self, but for country)
Half of communications is listening, and you can't listen with your mouth.

**Comment by haldiggs** [comment]
Visual Studio 2015, .Net 4.6 target.
In the BundleConfig.cs I am reading the Debug setting in the web.config in order to tell the bundler to optimize or not.

Partial code

```
AddDefaultIgnorePatterns(BundleTable.Bundles.IgnoreList);
AddDefaultFileExtensionReplacements(BundleTable.Bundles.FileExtensionReplacementList);

var nullBuilder = new NullBuilder();
var nullOrderer = new NullOrderer();

// Replace a default bundle resolver in order to the debugging HTTP-handler
// can use transformations of the corresponding bundle
BundleResolver.Current = new CustomBundleResolver();

//compress this stuff id DEBUG=false
bool isDebug = Valid.Core.Utilities.Miscellaneous.GetWebConfigCompilationSection().Debug;
BundleTable.EnableOptimizations = !isDebug;

/********** begin bundles **********/
var hbcHomeTemplatesBundle = new Bundle(HbsHomeTemplatesPath, new HTMLBarsTransformer());
hbcHomeTemplatesBundle.IncludeDirectory("~/Scripts/homeApp/templates", "*.hbs", true);
hbcHomeTemplatesBundle.Builder = nullBuilder;
hbcHomeTemplatesBundle.Orderer = nullOrderer;
bundles.Add(hbcHomeTemplatesBundle);
```

I can verify the JS and other bundles are working. This is the same way I used the old HandleBarsHelper with Ember 1.x which works fine.

The error occurs in the Jurasic.dll and the partial stack trace below
`[InvalidProgramException: Common Language Runtime detected an invalid program.]
   resolve(ScriptEngine , Scope , Object , FunctionInstance , Object[] ) +0
   Jurassic.Library.UserDefinedFunction.CallLateBound(Object thisObject, Object[] argumentValues) in c:\Users\Paul\Documents\Visual Studio 2012\Projects\jurassic\Jurassic\Library\Function\UserDefinedFunction.cs:240
   Jurassic.Library.FunctionInstance.CallWithStackTrace(String path, String function, Int32 line, Object thisObject, Object[] argumentValues) in c:\Users\Paul\Documents\Visual Studio 2012\Projects\jurassic\Jurassic\Library\Function\FunctionInstance.cs:195
   internalRequire(ScriptEngine , Scope , Object , FunctionInstance , Object[] ) +6059`

**Comment by haldiggs** [comment]
additionally... ok I have it working in a stripped down program... I think its because I'm using the BundleTransformer package to create the packages thats causing the issue. I will report back when I can confirm. Odd... I didn't know it wold matter. We use that package to customize some of whats included in specific folders but we can work around this.

**Comment by haldiggs** [comment]
finally... as it turns out everything runs fine as long as I use IISExpress for debugging but when I deploy or use the local IIS I get this set of errors. It must be a permission thing for Jurassic. Do you happen to have any information on this?

**Comment by haldiggs** [comment]
ok so I dumped the HtmlBars package in favor of just using the source project to find the issue. It does not happen as long as I run under IISExpress as I said before... but the line is when you attempt to grab the ember compiler

```
Line 24: Engine.Execute(GetEmbeddedResource("HTMLBarsHelper.Scripts
                 .ember-template-compiler.js", ass));

Exception Details: System.InvalidProgramException: 
     Common Language Runtime detected an invalid program.
```

and only happens when I run it under a real IIS web. The GetEmbeddedResource succeeds but Jurassic doesn't like it. I have tried running the web as an AppPoolIdentity as well as myself (an admin on the box) Its weird that it works under express settings. Sure wish I could figure this out

**Comment by kingpin2k** [comment]
Sorry, I'm in the middle of a hot fix at my work.  That particular error
looks weirdly like some sort of invalid .net version or x86 vs 64 bit
thing, but like I said, I'm playing another game right now, so I don't have
real time to look into it.

On Tue, Feb 2, 2016 at 12:15 PM, Hal Diggs notifications@github.com wrote:

> ok so I dumped the HtmlBars package in favor of just using the source
> project to find the issue. It does not happen as long as I run under
> IISExpress as I said before... but the line is when you attempt to grab the
> ember compiler
> 
> Line 24: Engine.Execute(GetEmbeddedResource("HTMLBarsHelper.Scripts.ember-template-compiler.js", ass));
> 
> Exception Details: System.InvalidProgramException: Common Language Runtime detected an invalid program.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kingpin2k/HTMLBarsHelper/issues/6#issuecomment-178766637
> .

## 

Daniel

Sent from my mind.

**Comment by haldiggs** [comment]
ok more digging... this is the exact issue
http://jurassic.codeplex.com/workitem/30025

**Comment by kingpin2k** [comment]
Bummer, that means we've got to get jurassic to release another version on
nuget.

On Tue, Feb 2, 2016 at 12:45 PM, Hal Diggs notifications@github.com wrote:

> ok more digging... this is the exact issue
> http://jurassic.codeplex.com/workitem/30025
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kingpin2k/HTMLBarsHelper/issues/6#issuecomment-178782913
> .

## 

Daniel

Sent from my mind.

**Comment by haldiggs** [comment]
did you see if they had one that fixes the issue? I didn't see it... but I'm not the most knowledgeable... I thought about trying to use the ClearScript project to replace Jurassic but eeesh... that thing is hairy

**Comment by kingpin2k** [comment]
I checked and they hadn't released since that pull request.  Admittedly
I've gone through 3 or 4 other .net javascript compilers, they all have
seemed to be a little shaky in one place or another.

On Tue, Feb 2, 2016 at 1:52 PM, Hal Diggs notifications@github.com wrote:

> did you see if they had one that fixes the issue? I didn't see it... but
> I'm not the most knowledgeable... I thought about trying to use the
> ClearScript project to replace Jurassic but eeesh... that thing is hairy
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kingpin2k/HTMLBarsHelper/issues/6#issuecomment-178813319
> .

## 

Daniel

Sent from my mind.

**Comment by haldiggs** [comment]
I wonder if I can set the bundling such that all of my javascript files compress but the handlebars are just injected raw. Not perfect... no serverside compile. Bummer. ok thanks for looking. I guess I am finally without a handlebars compiler unless I use Ember-CLI... ugh.

**Comment by kingpin2k** [comment]
Can you test this again against v2.0.0.1 (https://www.nuget.org/packages/HTMLBarsHelper/2.0.0.1), https://github.com/kingpin2k/HTMLBarsHelper/commit/8a1c632f6e0f8b6309cfc709cddd9376483a58af
